// some light shi idk

let Admin
let Name = "john"

Name = Admin

alert(Admin, 'Has become an admin.') // "john"


//-------------------------------------//
// variable naming

const ThePlanetWereOn = 'Earth'
const WebsiteVisitorName = 'Visitor'

//-------------------------------------//

let Number1 = '67'
let Number2 = '67'
let Corp = Corp

Number1 + Number2 + Corp


let Num1 = 41
let Num2 = 67

Num1 + Num2